name: Daily_Comic_Scraper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# 這裡給予僕人修改與寫入檔案的專屬權限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 複製程式碼到雲端伺服器
        uses: actions/checkout@v4

      - name: 安裝 Python 環境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 安裝僕人所需的套件
        run: |
          pip install -r requirements.txt

      - name: 執行漫畫抓取與排版任務
        run: python comic.py

      - name: 將精美展示牆掛上首頁
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m "管家報告：已更新今日網頁清單" || exit 0
          git pull --rebase
          git push
